In [1]:
import nfl_data_py as nfl
# To install
# pip install --upgrade nfl-data-py@git+https://github.com/cooperdff/nfl_data_py
import pandas as pd
pd.set_option('display.max_columns', None)

df_2022 = nfl.import_seasonal_data([2022])
df_2022

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_2pt_conversions,pacr,dakota,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr_x,special_teams_tds,fantasy_points,fantasy_points_ppr,games,tgt_sh,ay_sh,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
0,00-0019596,2022,REG,490,733,4694.0,25,9.0,22.0,160.0,3,2,4944.0,2315.0,237.0,61.906270,2,16.542028,1.570559,29,-1.0,1,2.0,2.0,5.0,-20.469321,0,0,1,0.0,0,0.0,0.0,16.0,0.0,0.0,-4.726016,0,0.000000,0.034483,0.061303,0.094636,0.0,271.66,271.66,17,0.001332,0.003150,0.000000,0.004518,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.175012
1,00-0022824,2022,REG,1,1,4.0,0,0.0,0.0,0.0,0,0,0.0,4.0,1.0,2.864477,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.0,0.16,0.16,1,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,NaN,NaN,0.000000,0.002352
2,00-0023459,2022,REG,350,542,3695.0,26,12.0,32.0,258.0,4,2,4341.0,1879.0,177.0,-6.309946,2,16.343032,1.501545,34,94.0,1,2.0,2.0,9.0,-7.814974,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.0,239.20,239.20,17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.166585
3,00-0024243,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,6,7,66.0,2,0.0,0.0,58.0,14.0,5.0,6.967597,1,5.423810,0.224952,0.201814,0.478697,0.0,20.60,26.60,6,0.034826,0.033507,0.020173,0.079044,0.047619,0.222222,0.070423,0.087500,0.134921,0.082540,0.328358,0.051556
4,00-0026143,2022,REG,309,461,3057.0,14,13.0,38.0,287.0,12,3,2763.0,1414.0,156.0,-24.760006,0,13.466402,0.737466,27,70.0,1,3.0,2.0,9.0,-11.035300,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.0,155.28,155.28,12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.155439
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
614,00-0038128,2022,REG,31,61,276.0,0,3.0,10.0,49.0,1,0,492.0,150.0,11.0,-38.837689,0,3.742161,-0.027944,27,123.0,1,2.0,2.0,8.0,-6.886303,0,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0.000000,0.000000,0.0,19.34,19.34,7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.049304
615,00-0038129,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,42,65,391.0,2,0.0,0.0,320.0,174.0,19.0,4.972101,0,17.468067,1.423885,1.105741,2.909847,0.0,51.10,93.10,14,0.101721,0.076849,0.087306,0.214062,0.097336,0.090909,0.091787,0.091703,0.094123,0.096051,0.611894,0.071070
616,00-0038134,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,228,1050.0,9,0.0,0.0,51.0,-14.810522,0,27,35,165.0,0,0.0,0.0,-75.0,221.0,6.0,-11.958612,0,-30.399037,1.030760,-0.466861,1.219338,0.0,175.50,202.50,15,0.068762,-0.019763,0.135086,0.087333,0.043160,0.000000,0.032609,0.028708,0.021580,0.034528,0.324165,0.147356
617,00-0038147,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,2,2,25.0,0,0.0,0.0,25.0,0.0,2.0,1.791362,0,1.000000,0.076923,0.223214,0.271635,0.0,2.50,4.50,1,0.071429,0.193798,0.000000,0.262182,0.155280,0.000000,0.200000,0.181818,0.077640,0.124224,0.892857,0.069402
618,00-0038149,2022,REG,0,0,0.0,0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.000000,0,0.000000,0.000000,0,0.0,0,0.0,0.0,0.0,0.000000,0,0,1,0.0,0,0.0,0.0,45.0,0.0,0.0,-0.519020,0,0.000000,0.035714,0.137615,0.149902,0.0,0.00,0.00,1,0.033333,0.129683,0.000000,0.153746,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [2]:
nfl.import_team_desc()

,team_abbr,team_name,team_id,team_nick,team_conf,team_division,team_color,team_color2,team_color3,team_color4,team_logo_wikipedia,team_logo_espn,team_wordmark,team_conference_logo,team_league_logo,team_logo_squared
0,ARI,Arizona Cardinals,3800,Cardinals,NFC,NFC West,#97233F,#000000,#ffb612,#a5acaf,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/ari.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
1,ATL,Atlanta Falcons,200,Falcons,NFC,NFC South,#A71930,#000000,#a5acaf,#a30d2d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/atl.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
2,BAL,Baltimore Ravens,325,Ravens,AFC,AFC North,#241773,#9E7C0C,#9e7c0c,#c60c30,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/bal.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
3,BUF,Buffalo Bills,610,Bills,AFC,AFC East,#00338D,#C60C30,#0c2e82,#d50a0a,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/buf.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
4,CAR,Carolina Panthers,750,Panthers,NFC,NFC South,#0085CA,#000000,#bfc0bf,#0085ca,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500-dark...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
5,CHI,Chicago Bears,810,Bears,NFC,NFC North,#0B162A,#E64100,#0b162a,#E64100,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/chi.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
6,CIN,Cincinnati Bengals,920,Bengals,AFC,AFC North,#FB4F14,#000000,#000000,#d32f1e,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/cin.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
7,CLE,Cleveland Browns,1050,Browns,AFC,AFC North,#FF3C00,#311D00,#a5acaf,#d32f1e,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/cle.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
8,DAL,Dallas Cowboys,1200,Cowboys,NFC,NFC East,#002244,#B0B7BC,#acc0c6,#a5acaf,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/dal.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
9,DEN,Denver Broncos,1400,Broncos,AFC,AFC West,#002244,#FB4F14,#00234c,#ff5200,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/den.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
10,DET,Detroit Lions,1540,Lions,NFC,NFC North,#0076B6,#B0B7BC,#000000,#004e89,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/det.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
11,GB,Green Bay Packers,1800,Packers,NFC,NFC North,#203731,#FFB612,#1c2d25,#eead1e,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/gb.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
12,HOU,Houston Texans,2120,Texans,AFC,AFC South,#03202F,#A71930,#00071c,#a30d2d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/hou.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
13,IND,Indianapolis Colts,2200,Colts,AFC,AFC South,#002C5F,#a5acaf,#013369,#9ba1a2,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/ind.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
14,JAX,Jacksonville Jaguars,2250,Jaguars,AFC,AFC South,#006778,#000000,#9f792c,#d7a22a,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/jax.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
15,KC,Kansas City Chiefs,2310,Chiefs,AFC,AFC West,#E31837,#FFB612,#000000,#e31837,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/kc.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
16,LA,Los Angeles Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
17,LAC,Los Angeles Chargers,4400,Chargers,AFC,AFC West,#007BC7,#ffc20e,#ffb612,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lac.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
18,LAR,Los Angeles Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
19,LV,Las Vegas Raiders,2520,Raiders,AFC,AFC West,#000000,#A5ACAF,#a6aeb0,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lv.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
20,MIA,Miami Dolphins,2700,Dolphins,AFC,AFC East,#008E97,#F58220,#005778,#008e97,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/mia.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
21,MIN,Minnesota Vikings,3000,Vikings,NFC,NFC North,#4F2683,#FFC62F,#e9bf9b,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/min.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
22,NE,New England Patriots,3200,Patriots,AFC,AFC East,#002244,#C60C30,#b0b7bc,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/ne.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
23,NO,New Orleans Saints,3300,Saints,NFC,NFC South,#D3BC8D,#000000,#9f8958,#000000,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/no.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
24,NYG,New York Giants,3410,Giants,NFC,NFC East,#0B2265,#A71930,#a5acaf,#012352,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
25,NYJ,New York Jets,3430,Jets,AFC,AFC East,#003F2D,#000000,NaN,NaN,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
26,OAK,Oakland Raiders,2520,Raiders,AFC,AFC West,#000000,#A5ACAF,#a6aeb0,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lv.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
27,PHI,Philadelphia Eagles,3700,Eagles,NFC,NFC East,#004C54,#A5ACAF,#acc0c6,#000000,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/phi.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
28,PIT,Pittsburgh Steelers,3900,Steelers,AFC,AFC North,#000000,#FFB612,#c60c30,#00539b,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/pit.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
29,SD,San Diego Chargers,4400,Chargers,AFC,AFC West,#007BC7,#ffc20e,#ffb612,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lac.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
30,SEA,Seattle Seahawks,4600,Seahawks,NFC,NFC West,#002244,#69be28,#a5acaf,#001532,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/sea.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
31,SF,San Francisco 49ers,4500,49ers,NFC,NFC West,#AA0000,#B3995D,#000000,#a5acaf,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/sf.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
32,STL,St. Louis Rams,2510,Rams,NFC,NFC West,#003594,#FFD100,#001532,#af925d,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/lar.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
33,TB,Tampa Bay Buccaneers,4900,Buccaneers,NFC,NFC South,#A71930,#322F2B,#000000,#ff7900,https://upload.wikimedia.org/wikipedia/en/thum...,https://a.espncdn.com/i/teamlogos/nfl/500/tb.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
34,TEN,Tennessee Titans,2100,Titans,AFC,AFC South,#002244,#4B92DB,#c60c30,#a5acaf,https://github.com/nflverse/nflverse-pbp/raw/m...,https://a.espncdn.com/i/teamlogos/nfl/500/ten.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...
35,WAS,Washington Commanders,5110,Commanders,NFC,NFC East,#5A1414,#FFB612,#000000,#5b2b2f,https://upload.wikimedia.org/wikipedia/commons...,https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png,https://github.com/nflverse/nflverse-pbp/raw/m...,https://github.com/nflverse/nflverse-pbp/raw/m...,https://raw.githubusercontent.com/nflverse/nfl...,https://github.com/nflverse/nflverse-pbp/raw/m...

In [9]:
df_schedule = nfl.import_schedules([2022])
df_schedule

,game_id,season,game_type,week,gameday,weekday,gametime,away_team,away_score,home_team,home_score,location,result,total,overtime,old_game_id,gsis,nfl_detail_id,pfr,pff,espn,ftn,away_rest,home_rest,away_moneyline,home_moneyline,spread_line,away_spread_odds,home_spread_odds,total_line,under_odds,over_odds,div_game,roof,surface,temp,wind,away_qb_id,home_qb_id,away_qb_name,home_qb_name,away_coach,home_coach,referee,stadium_id,stadium
6137,2022_01_BUF_LA,2022,REG,1,2022-09-08,Thursday,20:20,BUF,31.0,LA,10.0,Home,-21.0,41.0,0.0,2022090800,NaN,NaN,202209080ram,NaN,401437654,5879.0,7,7,-117.0,106.0,-1.0,-112.0,101.0,51.5,-101.0,-111.0,0,dome,matrixturf,NaN,NaN,00-0034857,00-0026498,Josh Allen,Matthew Stafford,Sean McDermott,Sean McVay,Carl Cheffers,LAX01,SoFi Stadium
6138,2022_01_NO_ATL,2022,REG,1,2022-09-11,Sunday,13:00,NO,27.0,ATL,26.0,Home,-1.0,53.0,0.0,2022091100,NaN,NaN,202209110atl,NaN,401437650,5880.0,7,7,-228.0,201.0,-6.0,-103.0,-107.0,43.5,-104.0,-108.0,1,closed,fieldturf,NaN,NaN,00-0031503,00-0032268,Jameis Winston,Marcus Mariota,Dennis Allen,Arthur Smith,Alex Kemp,ATL97,Mercedes-Benz Stadium
6139,2022_01_CLE_CAR,2022,REG,1,2022-09-11,Sunday,13:00,CLE,26.0,CAR,24.0,Home,-2.0,50.0,0.0,2022091101,NaN,NaN,202209110car,NaN,401437651,5881.0,7,7,114.0,-125.0,2.5,-112.0,102.0,42.5,-113.0,100.0,0,outdoors,grass,NaN,NaN,00-0033119,00-0034855,Jacoby Brissett,Baker Mayfield,Kevin Stefanski,Matt Rhule,Brad Rogers,CAR00,Bank of America Stadium
6140,2022_01_SF_CHI,2022,REG,1,2022-09-11,Sunday,13:00,SF,10.0,CHI,19.0,Home,9.0,29.0,0.0,2022091102,NaN,NaN,202209110chi,NaN,401437647,5882.0,7,7,-248.0,217.0,-6.5,100.0,-111.0,38.0,-103.0,-109.0,0,outdoors,grass,NaN,NaN,00-0037012,00-0036945,Trey Lance,Justin Fields,Kyle Shanahan,Matt Eberflus,Clay Martin,CHI98,Soldier Field
6141,2022_01_PIT_CIN,2022,REG,1,2022-09-11,Sunday,13:00,PIT,23.0,CIN,20.0,Home,-3.0,43.0,1.0,2022091103,NaN,NaN,202209110cin,NaN,401437634,5883.0,7,7,264.0,-308.0,7.5,-119.0,107.0,44.5,101.0,-113.0,1,outdoors,fieldturf,NaN,NaN,00-0033869,00-0036442,Mitch Trubisky,Joe Burrow,Mike Tomlin,Zac Taylor,Shawn Hochuli,CIN00,Paycor Stadium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6416,2022_20_CIN_BUF,2022,DIV,20,2023-01-22,Sunday,15:00,CIN,27.0,BUF,10.0,Home,-17.0,37.0,0.0,2023012200,NaN,NaN,202301220buf,NaN,401438007,6159.0,7,7,226.0,-259.0,6.0,-107.0,-103.0,48.5,-107.0,-105.0,0,outdoors,a_turf,32.0,4.0,00-0036442,00-0034857,Joe Burrow,Josh Allen,Zac Taylor,Sean McDermott,Carl Cheffers,BUF00,New Era Field
6417,2022_20_DAL_SF,2022,DIV,20,2023-01-22,Sunday,18:30,DAL,12.0,SF,19.0,Home,7.0,31.0,0.0,2023012201,NaN,NaN,202301220sfo,NaN,401438006,6160.0,6,8,164.0,-183.0,3.5,-107.0,-103.0,46.5,-105.0,-107.0,0,outdoors,grass,55.0,19.0,00-0033077,00-0037834,Dak Prescott,Brock Purdy,Mike McCarthy,Kyle Shanahan,Bill Vinovich,SFO01,Levi's Stadium
6418,2022_21_SF_PHI,2022,CON,21,2023-01-29,Sunday,15:00,SF,7.0,PHI,31.0,Home,24.0,38.0,0.0,2023012900,NaN,NaN,202301290phi,NaN,401438009,6161.0,7,8,133.0,-147.0,2.5,105.0,-116.0,45.0,-114.0,101.0,0,outdoors,grass,52.0,14.0,00-0037834,00-0036389,Brock Purdy,Jalen Hurts,Kyle Shanahan,Nick Sirianni,John Hussey,PHI00,Lincoln Financial Field
6419,2022_21_CIN_KC,2022,CON,21,2023-01-29,Sunday,18:30,CIN,20.0,KC,23.0,Home,3.0,43.0,0.0,2023012901,NaN,NaN,202301290kan,NaN,401438008,6162.0,7,8,119.0,-131.0,2.0,-103.0,-107.0,48.5,-106.0,-106.0,0,outdoors,grass,22.0,13.0,00-0036442,00-0033873,Joe Burrow,Patrick Mahomes,Zac Taylor,Andy Reid,Ron Torbert,KAN00,GEHA Field at Arrowhead Stadium
6420,2022_22_KC_PHI,2022,SB,22,2023-02-12,Sunday,18:30,KC,38.0,PHI,35.0,Neutral,-3.0,73.0,0.0,2023021200,NaN,NaN,202302120phi,NaN,401438030,6163.0,14,14,104.0,-115.0,1.0,-103.0,-107.0,51.0,-104.0,-108.0,0,closed,grass,NaN,NaN,00-0033873,00-0036389,Patrick Mahomes,Jalen Hurts,Andy Reid,Nick Sirianni,Carl Cheffers,PHO00,State Farm Stadium

In [5]:
df_schedule.columns

Index(['game_id', 'season', 'game_type', 'week', 'gameday', 'weekday',
       'gametime', 'away_team', 'away_score', 'home_team', 'home_score',
       'location', 'result', 'total', 'overtime', 'old_game_id', 'gsis',
       'nfl_detail_id', 'pfr', 'pff', 'espn', 'ftn', 'away_rest', 'home_rest',
       'away_moneyline', 'home_moneyline', 'spread_line', 'away_spread_odds',
       'home_spread_odds', 'total_line', 'under_odds', 'over_odds', 'div_game',
       'roof', 'surface', 'temp', 'wind', 'away_qb_id', 'home_qb_id',
       'away_qb_name', 'home_qb_name', 'away_coach', 'home_coach', 'referee',
       'stadium_id', 'stadium'],
      dtype='object')

In [7]:
ids = nfl.import_ids()
ids

,mfl_id,sportradar_id,fantasypros_id,gsis_id,pff_id,sleeper_id,nfl_id,espn_id,yahoo_id,fleaflicker_id,cbs_id,pfr_id,cfbref_id,rotowire_id,rotoworld_id,ktc_id,stats_id,stats_global_id,fantasy_data_id,swish_id,name,merge_name,position,team,birthdate,age,draft_year,draft_round,draft_pick,draft_ovr,twitter_username,height,weight,college,db_season
0,15702,93147c90-09c8-471d-a6b2-0b9d19739ba1,24740.0,00-0038400,NaN,9230.0,NaN,NaN,40220.0,NaN,2963945.0,McKeTa01,tanner-mckee-1,16686.0,NaN,NaN,40220.0,0.0,NaN,1123521.0,Tanner McKee,tanner mckee,QB,PHI,2000-04-27,23.6,2023.0,6.0,11.0,188.0,NaN,78.0,231.0,Stanford,2023
1,16148,38475bfa-9773-4c3b-9157-a0dbd576fa22,22900.0,00-0039150,NaN,9228.0,NaN,NaN,40029.0,NaN,3161957.0,YounBr01,bryce-young-1,16807.0,NaN,1456.0,40029.0,0.0,NaN,1213257.0,Bryce Young,bryce young,QB,CAR,2001-07-25,22.4,2023.0,1.0,1.0,1.0,NaN,70.0,204.0,Alabama,2023
2,16149,4c8a2f7e-f982-4eca-9d52-cf53df6985a4,22987.0,00-0039152,NaN,9999.0,NaN,NaN,40068.0,NaN,2964377.0,LeviWi00,will-levis-1,16665.0,NaN,1402.0,40068.0,0.0,NaN,1116663.0,Will Levis,will levis,QB,TEN,1999-06-27,24.4,2023.0,2.0,2.0,33.0,NaN,76.0,229.0,Kentucky,2023
3,16150,7e91086f-9ca4-4bd9-a099-b88b2f37e6c6,23071.0,00-0039163,NaN,9758.0,NaN,NaN,40030.0,NaN,3163079.0,StroCJ00,cj-stroud-1,16886.0,NaN,1403.0,40030.0,0.0,NaN,1214084.0,C.J. Stroud,cj stroud,QB,HOU,2001-10-03,22.2,2023.0,1.0,2.0,2.0,NaN,75.0,218.0,Ohio State,2023
4,16151,25b10007-802d-4ebb-8314-3eb7b24ddc37,24332.0,00-0038550,NaN,9998.0,NaN,NaN,40096.0,NaN,2805110.0,HookHe00,hendon-hooker-1,16905.0,NaN,1404.0,40096.0,0.0,NaN,976966.0,Hendon Hooker,hendon hooker,QB,DET,1998-01-13,25.9,2023.0,3.0,5.0,68.0,NaN,75.0,220.0,Tennessee,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11390,972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Doug Brien,doug brien,PK,NOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
11391,978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jeremy Brigham,jeremy brigham,TE,OAK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
11392,984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Vincent Brisby,vincent brisby,WR,FA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
11393,990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bubby Brister,bubby brister,QB,KCC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
11394,996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lorenzo Bromell,lorenzo bromell,DL,MIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023

In [8]:
ids[ids['gsis_id'] == '00-0019596']

,mfl_id,sportradar_id,fantasypros_id,gsis_id,pff_id,sleeper_id,nfl_id,espn_id,yahoo_id,fleaflicker_id,cbs_id,pfr_id,cfbref_id,rotowire_id,rotoworld_id,ktc_id,stats_id,stats_global_id,fantasy_data_id,swish_id,name,merge_name,position,team,birthdate,age,draft_year,draft_round,draft_pick,draft_ovr,twitter_username,height,weight,college,db_season
8212,5848,41c44740-d0f6-44ab-8347-3b5d515e5ecf,9603.0,00-0019596,698.0,167.0,tombrady/2504211,2330.0,5228.0,309.0,187741.0,BradTo00,tom-brady-1,1350.0,1163.0,NaN,5228.0,25347.0,4314.0,25347.0,Tom Brady,tom brady,QB,FA,1977-08-03,46.3,2000.0,6.0,33.0,199.0,NaN,76.0,225.0,Michigan,2023